### ISSUE TITLE
RootNode子节点添加删除后，NodeFlatIndex.VisibleFlatIndex数据与RootNode不一致，导致显示错乱

### ISSUE THREAD

**Issue by FlyAwayL** [jack-cook/LinearTree#1]
hi，Jack
  在自己的项目中用了你的这个数据结构，展示分层列表好完美，谢谢。
  但是现在我遇到一个问题，在Recyclerview中添加和删除子节点后，显示的数据位置不对。debug看了RootNode里面的数据位置是符合预期的，但是Index中的没有随RootNode改变而更新。想请教下大神，谢谢。

**Comment by FlyAwayL** [comment]
现在改成每次数据修改后，重新生成Index，这样上面的问题解决了。不知道性能有没影响，或者有没更好的办法。
 index.invalidate();
 index = rootNode.getFlatIndex().getVisibleIndex();

**Comment by jack-cook** [comment]
应该是个bug,性能会差一点，数据量不多的话没什么影响。谢谢反馈，最近比较忙，过段时间再改。

**Comment by jack-cook** [comment]
@FlyAwayL 
改了点东西，不知道有没有覆盖你的问题，可以试试新版本。
